# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - binary: contest
    dir: ./src/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
archives:
  - replacements:
      darwin: macOS
      amd64: x86_64
brews:
  - name: contest
    tap:
      owner: cadast
      name: homebrew-contest
      branch: main
    folder: Formula
    homepage: "https://www.github.com/cadast/contest"
    description: "A simple tool for contract testing web APIs"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
